name: Update config.json

on:
  issues:
    types: [opened]

jobs:
  update-config:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Guardar JSON del issue en config.json
        run: |
          body=$(jq -r .issue.body <<< '${{ toJson(github.event) }}')
          # Eliminar la primera lÃ­nea "UPDATE_CONFIG_JSON"
          cleaned=$(printf "%s" "$body" | tail -n +2)
          printf "%s" "$cleaned" > config.json

      - name: Commit & push
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add config.json
          git commit -m "Update config.json desde Power Automate"
          git push

