name: Update config.json

on:
  issues:
    types: [opened]

jobs:
  update-config:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositorio
        uses: actions/checkout@v3

      - name: Extraer contenido del issue
        run: |
          echo "${{ github.event.issue.body }}" > config.json

      - name: Commit y push
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add config.json
          git commit -m "Update config.json desde Power Automate"
          git push
